AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Type d'instance EC2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: CleTo
    Description: Nom de la paire de clés pour accéder à l'instance EC2

Resources:
  SecurityGroupGT:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Autorise SSH et HTTP
      VpcId: !Ref VPCGT
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Autorise SSH depuis toutes les IP (à restreindre pour la sécurité)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Autorise HTTP


  VPCGT:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  SubnetGT:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCGT
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  EC2GT:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0e54671bdf3c8ed8d
      SubnetId: !Ref SubnetGT
      SecurityGroupIds:
        - !Ref SecurityGroupGT
      Tags:
        - Key: Name
          Value: EC2GT
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          service -httpd start
          chkconfig httpd on





  
